### ISSUE TITLE
Remove the -n printed only while running from sleepwatcher

### ISSUE THREAD

**Issue by spygi** [spygi/personal#2]
Try printf instead of echo -n

**Comment by spyros86** [comment]
I am batman!

Spyros Vlachos

**Comment by spygi** [comment]
haha vlaka!

**Comment by spyros86** [comment]
egines bashistas?

**Comment by spygi** [comment]
exw grapsei kata kairous vlakeioules scriptakia alla oxi kati sovaro. Kai ka8e fora ksexnaw syntax kai prepei na googlarw ;)
